# Generated by Django 3.2 on 2021-12-10 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='FriendsID',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='HobbiesID',
        ),
        migrations.AddField(
            model_name='friends',
            name='FriendsOneID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friends',
            name='FriendsTwoID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
