# Generated by Django 3.2 on 2021-12-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0004_user_hobbiesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='HobbiesID',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
