# Generated by Django 3.2 on 2021-12-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0007_auto_20211212_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobbies',
            old_name='HobbiesID',
            new_name='id',
        ),
    ]
