# Generated by Django 3.2 on 2021-12-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0008_rename_hobbiesid_hobbies_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hobby',
            new_name='hobbyString',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userID',
            new_name='id',
        ),
    ]
