# Generated by Django 3.2 on 2021-12-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0009_auto_20211213_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobbies',
            options={'verbose_name': 'hobby message', 'verbose_name_plural': 'hobby message'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user message', 'verbose_name_plural': 'user message'},
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=32),
        ),
    ]
